#!/usr/bin/env bash

printf "Content-type: text/plain; charset=iso-8859-1\n\n"

printf "hello world\n"

env | grep "^HTTP"


if [[ -p /dev/stdin ]]; then ## -p : file is a pipe
  printf "found stdin \n"
  cat -

  echo

fi


