#!/usr/bin/env bash

function echo_response_default_headers() { 
  # DATE=$(date +"%a, %d %b %Y %H:%M:%S %Z")
  echo -e "Date: $(date -u "+%a, %d %b %Y %T GMT")\r"
  # echo -e "Expires: $(date -u "+%a, %d %b %Y %T GMT")\r"
  echo -e "Expires: 0\r"
  echo -e "Connection: close\r"
  echo -e "Cache-Control: no-cache, no-store, must-revalidate\r"
  echo -e "Pragma: no-cache\r"
}
export -f echo_response_default_headers

function echo_content_response() {
  local content="$(cat)"
  local content_type="${1-"text/html"}"
  echo_response_status_line
  echo_response_default_headers
  echo -e "Access-Control-Allow-Origin: *\r"
  echo -e "Content-Type: ${content_type}; charset=utf-8\r"
  echo -e "Content-Length: $((${#content}+1))\r"
  echo -e "\r"
  echo "${content}"
  echo -e "\r"
}
export -f echo_content_response

function echo_redirect_response() { 
  local LOCATION="$1"
  echo_response_status_line 302 Found
  echo_response_default_headers
  echo -e "Location: ${LOCATION}\r"
  echo -e "Content-Length: 0\r"
  echo -e "\r"
}
export -f echo_redirect_response

function echo_response_status_line() { 
  local STATUS_CODE STATUS_TEXT
  STATUS_CODE=${1-200}
  STATUS_TEXT=${2-OK}
  log "response: ${STATUS_CODE} ${STATUS_TEXT}"
  echo -e "HTTP/1.0 ${STATUS_CODE} ${STATUS_TEXT}\r"
}
export -f echo_response_status_line


function get_header_value() { 
  header_key="$1"
  sed -e "/^${header_key}/I!d" \
      -e "s/^${header_key}: \(.*\)\$/\1/gi"
}
export -f get_header_value

function urldecode() {
  INPUT="$@"
  url_encoded="${INPUT//+/ }"
  printf '%b\n' "${url_encoded//%/\\x}"
}
export -f urldecode

function urlencode() {
  echo -n "$@" | while IFS= read -n 1 C; do 
    case $C in
        [a-zA-Z0-9.~_-]) printf "$C" ;;
        *) printf '%%%02X' "'$C" ;; 
    esac
  done
  printf '\n'
}
export -f urlencode

