#!/usr/bin/env bash

set -o errexit  # abort when any commands exits with error
set -o pipefail # abort when any command in a pipe exits with error
set -o nounset  # abort when any unset variable is used
set -o errtrace # inherits trap on ERR in function and subshell
set -f # prevent bash from expanding glob
trap 'echo status:$? line:$LINENO line:$BASH_LINENO command:"$BASH_COMMAND" functions:$(printf " %s" ${FUNCNAME[@]:-});exit 1' ERR

printf "Content-type: text/plain; charset=iso-8859-1\n\n"

printf "hello world\n"
echo "${QUERY_STRING:-""}" >&2
echo "${REQUEST_URI:-""}" >&2

env | grep "^HTTP" >&2
# false

if [[ -p /dev/stdin ]]
then
    cat - | sed -e 's/^/---/g' -e 's/$/---/g'
fi




echo "==========================================="
env | grep "^SOCAT"



